const createdDate = '2020-09-17';
const workflowColumns = [
    'Client Name',
    'Run ID',
    'Ticket Number',
    'File Upload ID',
    'File Name',
    'Layout ID',
    'Created Date',
    'Created By'
];

const clientSetupColumns = [
    'Client Name',
    'Client Description',
    'File Type Details',
    'Project Types',
    'Risk Adjustment LOBs',
    'Network Indicators',
    'Created By',
    'Created Date',
    'Modified By',
    'Modified Date',
    'Active',
    'Action'
];

const chaseFileLayoutSetupColumns = [
    'Layout Id',
    'Client Name',
    'File Type Detail',
    'Risk Adjustment LOB',
    'Project Type',
    'Network Indicator',
    'UCL Standard Layout',
    'Active',
    'Action'
];
const extractConfigurationColumns = [
    'SN.',
    'Risk Adjustment LOB',
    'Project Type',
    'Extract Name'
];

const nonUCLColumns = [
    'RecordType',
    'ChaseID',
    'PlanID',
    'MemberID',
    'MasterMemberID',
    'SubscriberIndicator',
    'SubscriberMemberID',
    'MemberLast',
    'MemberFirst',
    'MemberMiddle',
    'MemberSuffix',
    'MemberDOB',
    'MemberDOD',
    'MemberGender',
    'MemberEffectiveDate',
    'MemberTerminationDate',
    'MemberAddress1',
    'MemberAddress2',
    'MemberCity',
    'MemberState',
    'MemberZIP',
    'MemberZIP4',
    'MemberCountyCode',
    'MemberCountryCode',
    'MemberPhone',
    'MemberPBP',
    'HICN',
    'MemberSSN',
    'MedicaidMemberID',
    'CSRCode',
    'ESRDFlag',
    'HospiceFlag',
    'WorkingAgedFlag',
    'InstitutionalFlag',
    'PartCRiskScore',
    'PartDRiskScore',
    'RAFactorType',
    'GroupCode',
    'MemberPCPNPI',
    'MemberPCPID',
    'MemberPCPLastName',
    'MemberPCPFirstName',
    'MemberPCPMiddleName',
    'MemberPCPNameSuffix',
    'MemberPCPAddress1',
    'MemberPCPAddress2',
    'MemberPCPCity',
    'MemberPCPState',
    'MemberPCPPostalCode',
    'MemberPCPZip4',
    'MemberPCPCountry',
    'MemberPCPCountrySubdivision',
    'MemberPCPPhone',
    'MemberPCPGroupProviderName',
    'MemberPCPGroupProviderID',
    'ProviderID',
    'ProviderNPI',
    'ProviderLast',
    'ProviderFirst',
    'ProviderMiddle',
    'ProviderSuffix',
    'ProviderTitle',
    'ProviderAddress1',
    'ProviderAddress2',
    'ProviderCity',
    'ProviderState',
    'ProviderZip',
    'ProviderZip4',
    'ProviderCountryCode',
    'ProviderCountrySubdivision',
    'ProviderCountyName',
    'ProviderPhone',
    'ProviderFax',
    'ProviderType',
    'ProviderSpecialtyType1',
    'ProviderSpecialtyType2',
    'ProviderSpecialtyType3',
    'ProviderTIN',
    'ProviderSSN',
    'GroupProviderID',
    'GroupProviderName',
    'PrimaryLocationFlag',
    'VendorID',
    'DateOfServiceStart',
    'DateOfServiceEnd',
    'ImageFileName',
    'RADVEnrolleeID',
    'HCC',
    'HEDISMeasureID',
    'ProjectCodeType',
    'HostPlanCode',
    'HomePlanCode',
    'Metal',
    'RetrievalRank',
    'RetrievalStratification',
    'RetrievalSuspectSource',
    'UseForMRA',
    'UseForCRA',
    'UseForHEDIS',
    'UseForRADV',
    'Filler1',
    'Filler2',
    'Filler3',
    'PBG_NUMBER',
    'PBG_STATUS',
    'ProviderTerritory'
];
const nonUCLMappingValues = [
    '\'D\'',
    'CHASE_ID',
    'HPLAN',
    'MEMBER_ID',
    '',
    '',
    '',
    'MEMBER_LAST_NAME',
    'MEMBER_FIRST_NAME',
    '',
    '',
    'MEMBER_DOB',
    '',
    'GENDER',
    '',
    '',
    'MEMBER_ADDRESS',
    '',
    'MEMBER_CITY',
    'MEMBER_STATE',
    'MEMBER_ZIP',
    '',
    '',
    '',
    '',
    'replicate(\'0\', 3 - len(PBP)) + PBP',
    'MBI',
    '',
    '',
    '',
    'ESRD',
    '',
    '',
    '',
    '',
    '',
    'RAFT_CD',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    // tslint:disable-next-line: max-line-length
    'LTRIM(RTRIM(PROVIDER_ID))+ \'_\'+ CASE WHEN LEN(client_source_id) = 2 AND substring(client_source_id,1,1) = \'0\'  THEN REPLACE(LTRIM(RTRIM(Client_Source_ID)),\'0\',\'\')   WHEN LEN(client_source_id) = 2 AND substring(client_source_id,1,1) != \'0\'  THEN client_source_id  ELSE client_source_id END',
    'PROVIDER_NPI',
    'PROVIDER_LAST_NAME',
    'PROVIDER_FIRST_NAME',
    '',
    '',
    '',
    'PROVIDER_ADDRESS',
    '',
    'PROVIDER_CITY',
    'PROVIDER_STATE',
    'PROVIDER_ZIP',
    '',
    '',
    '',
    '',
    'REPLACE(LTRIM(RTRIM(PROVIDER_PHONE)),\'-\',\'\')',
    '',
    // tslint:disable-next-line: max-line-length
    'CASE LTRIM(RTRIM(CHART_TYPE)) WHEN \'PCP - FAC\' THEN \'PCP\'           WHEN \'SPEC - FAC\' THEN \'SPEC\'           ELSE LTRIM(RTRIM(CHART_TYPE)) END',
    'PROVIDER_SPECIALTY',
    '',
    '',
    'PROVIDER_TIN',
    '',
    'PBG_NUMBER',
    'PBG_NAME',
    '\'0\'',
    'VENDOR',
    '\'01-01-2019\'',
    '',
    '',
    '',
    '',
    '',
    '\'Retrospective\'',
    '',
    '',
    '',
    '',
    'SUBSTRING(LTRIM(RTRIM(CATEGORY)),3,LEN(CATEGORY))',
    '',
    '\'Y\'',
    '\'N\'',
    '\'N\'',
    '\'N\'',
    // tslint:disable-next-line: max-line-length
    'CASE LTRIM(RTRIM(CHART_TYPE)) WHEN \'PCP\' THEN \'P\'    WHEN \'SPEC\' THEN \'P\'    WHEN \'Phys\' THEN \'P\'    WHEN \'IP\' THEN \'HI\'    WHEN \'OP\' THEN \'HO\'    WHEN \'SNF\' THEN \'HI\'    WHEN \'SPEC - FAC\' THEN \'P\'    WHEN \'PCP - FAC\' THEN \'P\'    ELSE LTRIM(RTRIM(CHART_TYPE)) END',
    'ENTITY',
    'ON_OFF_IND',
    'PBG_NUMBER',
    'STATUS',
    'PROVIDER_TERRITORY'
];

export {
    clientSetupColumns,
    chaseFileLayoutSetupColumns,
    createdDate,
    extractConfigurationColumns,
    workflowColumns,
    nonUCLColumns,
    nonUCLMappingValues
};
